[package]
name = "shapeshift-rs"
version = "0.1.0"
authors = ["user"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.13"
hyper-tls = "0.4.0"
tokio = { version = "0.2.9", features = ["full"] }
